stages:
  - test

test:
  stage: test
  image: python:3.10 # Use an official Python image
  variables:
    VIRTUAL_ENV: venv
  before_script:
    - python -m venv $VIRTUAL_ENV
    - source $VIRTUAL_ENV/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest --cov=app --cov-report=xml
  after_script:
    - deactivate
